import React, { createContext, useContext, useState, useEffect } from 'react';
import { useAuth } from './AuthProvider';

export type LanguageCode = 'en' | 'ig' | 'yo' | 'ha' | 'pcm' | 'pidgin' | 'fr' | 'zh';

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => Promise<void>;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    // Menu items
    "City Faces": "City Faces",
    "Fidelity Wallet": "Fidelity Wallet",
    "Purple Fleet": "Purple Fleet",
    "SANDALSroyalle Hotels & Suites": "SANDALSroyalle Hotels & Suites",
    "Carry-Go Cargo": "Carry-Go Cargo",
    "Thrift Savings": "Thrift Savings",
    "Audio Archive": "Audio Archive",
    "Creative Lab": "Creative Lab",
    "Hardware Audit": "Hardware Audit",
    "Aba History": "Aba History",
    "City Registry": "City Registry",
    "Oracle Hub": "Oracle Hub",
    "Home Node": "Home Node",
    // General Settings
    "System Settings": "System Settings",
    "User Preferences": "User Preferences",
    "Preferred Dialect": "Preferred Dialect",
    "Notification Mesh": "Notification Mesh",
    "Protocol Interface": "Protocol Interface",
    "Linguistic preference synced": "Linguistic preference synced",
    "Sync fault in preferences": "Sync fault in preferences",
    "Notifications": "Notifications",
    "Dark Mode": "Dark Mode",
    "Logout": "Logout",
    "Login": "Login",
    "Sign Up": "Sign Up",
    "Profile": "Profile",
    "No notifications": "No notifications",
    "Support Center": "Support Center",
    "Legal Protocols": "Legal Protocols",
    "About FindAba": "About FindAba",
    "Explore Aba": "Explore Aba",
    "Find Opportunities": "Find Opportunities",
    "Search businesses": "Search businesses...",
    "Trending Market Days": "Trending Market Days",
    "Aba History description": "Aba is a vibrant commercial, industrial, and cultural power hub.",
    "System Status": "System Status",
    "Save Preferences": "Save Preferences",
    "English (Official)": "English (Official)",
    "Igbo (Zonal)": "Igbo (Zonal)",
    "Pidgin (Regional)": "Pidgin (Regional)",
    "Yoruba": "Yoruba",
    "Hausa": "Hausa",
    "French": "French",
    "Chinese": "Chinese",
    "Edit Profile": "Edit Profile",
    "Security & Cryptography": "Security & Cryptography"
  },
  ig: {
    "City Faces": "Ihu Obodo",
    "Fidelity Wallet": "Akpa Ego Fidelity",
    "Purple Fleet": "Ụgbọ Purple",
    "SANDALSroyalle Hotels & Suites": "Ụlọ Obịa Sandals",
    "Carry-Go Cargo": "Ibu Carry-Go",
    "Thrift Savings": "Ego Nchekwa (Ajo)",
    "Audio Archive": "Ebe Ndebe Ụda",
    "Creative Lab": "Ụlọ Ọrụ Nka",
    "Hardware Audit": "Nlele Ngwaika",
    "Aba History": "Akụkọ Aba",
    "City Registry": "Akwụkwọ Ndekọ Obodo",
    "Oracle Hub": "Ebe Oracle",
    "Home Node": "Isi Noo (Ụlọ)",
    "System Settings": "Nhazi Usoro",
    "User Preferences": "Ihe Onye Ọrụ Họrọ",
    "Preferred Dialect": "Asụsụ Kacha Mma",
    "Notification Mesh": "Ebe Ozi Nkesa",
    "Protocol Interface": "Interface Usoro",
    "Linguistic preference synced": "Emebanyela asụsụ ị họrọ",
    "Sync fault in preferences": "Nsogbu n'ịchekwa asụsụ",
    "Notifications": "Ịma Ọkwa",
    "Dark Mode": "Ụdị gbara Ọchịchịrị",
    "Logout": "Wụpụ",
    "Login": "Banye",
    "Sign Up": "Debanye aha",
    "Profile": "Profaịlụ",
    "No notifications": "Ozi ọ bụla adịghị",
    "Support Center": "Ebe Nkwado",
    "Legal Protocols": "Usoro Iwu",
    "About FindAba": "Gbasara FindAba",
    "Explore Aba": "Nyochaa Obodo Aba",
    "Find Opportunities": "Chọta Ohere",
    "Search businesses": "Chọọ ụlọ ọrụ...",
    "Trending Market Days": "Ahịa Ndị Na-ewu Ewu",
    "Aba History description": "Aba bụ ebe pụrụ iche maka azụmahịa, nka na ọdịnala.",
    "System Status": "Ọnọdụ Usoro",
    "Save Preferences": "Chekwa Ihe Ndị a",
    "English (Official)": "Bekee (English)",
    "Igbo (Zonal)": "Asụsụ Igbo",
    "Pidgin (Regional)": "Pidgin (Nke anyị)",
    "Yoruba": "Asụsụ Yoruba",
    "Hausa": "Asụsụ Hausa",
    "French": "Asụsụ French",
    "Chinese": "Asụsụ Chinese",
    "Edit Profile": "Mezie Profaịlụ",
    "Security & Cryptography": "Nchebe & Kriptografi"
  },
  yo: {
    "City Faces": "Oju Ilu",
    "Fidelity Wallet": "Apo Kadi Fidelity",
    "Purple Fleet": "Ọkọ Purple",
    "SANDALSroyalle Hotels & Suites": "Iyẹwu Sandals",
    "Carry-Go Cargo": "Gbe Lọ Erù",
    "Thrift Savings": "Ifowopamọ Aajo",
    "Audio Archive": "Ile-ijọsin Ohun",
    "Creative Lab": "Yara Ọgangan",
    "Hardware Audit": "Ayẹwo Hardware",
    "Aba History": "Itan Aba",
    "City Registry": "Iforukọsilẹ Ilu",
    "Oracle Hub": "Ibudo Oracle",
    "Home Node": "Oju Ile",
    "System Settings": "Eto Eto",
    "User Preferences": "Eto Oloore",
    "Preferred Dialect": "Ede ti o fẹ",
    "Notification Mesh": "Eto Ifitonileti",
    "Protocol Interface": "Eto Ilana",
    "Linguistic preference synced": "Eto ede rẹ ti fipamọ",
    "Sync fault in preferences": "Aṣiṣe wa ninu fifipamọ ede",
    "Notifications": "Awọn ifitonileti",
    "Dark Mode": "Ipo Okun",
    "Logout": "Jade",
    "Login": "Wọle",
    "Sign Up": "Forukọsilẹ",
    "Profile": "Akọọlẹ Mi",
    "No notifications": "Ko si ifitonileti",
    "Support Center": "Ibudo Atilẹyin",
    "Legal Protocols": "Awọn ilana Ofin",
    "About FindAba": "Nipa FindAba",
    "Explore Aba": "Ṣawari Aba",
    "Find Opportunities": "Wa Awọn Anfaani",
    "Search businesses": "Ṣawari awọn iṣowo...",
    "Trending Market Days": "Awọn Ọjọ Ọja",
    "Aba History description": "Aba jẹ olu-ilu ti iṣowo, ile-iṣẹ ati aṣa labẹ ilẹ.",
    "System Status": "Ipo Eto",
    "Save Preferences": "Fi Eto pamọ",
    "English (Official)": "Ede Gẹẹsi",
    "Igbo (Zonal)": "Ede Igbo",
    "Pidgin (Regional)": "Ede Pidgin",
    "Yoruba": "Ede Yoruba",
    "Hausa": "Ede Hausa",
    "French": "Ede Faransé",
    "Chinese": "Ede Kannada (Chinese)",
    "Edit Profile": "Ṣatunkọ Akọọlẹ",
    "Security & Cryptography": "Aabo & Cryptography"
  },
  ha: {
    "City Faces": "Fuskar Birni",
    "Fidelity Wallet": "Asusun Fidelity",
    "Purple Fleet": "Jirgin Purple",
    "SANDALSroyalle Hotels & Suites": "Otal din Sandals",
    "Carry-Go Cargo": "Gudanar da Kaya",
    "Thrift Savings": "Adashin Gata",
    "Audio Archive": "Rukunin Sauti",
    "Creative Lab": "Gwajen Ƙirƙira",
    "Hardware Audit": "Binciken Hardware",
    "Aba History": "Tarihin Aba",
    "City Registry": "Rafi na Birni",
    "Oracle Hub": "Tashar Oracle",
    "Home Node": "Gida",
    "System Settings": "Saitunan Tsari",
    "User Preferences": "Zaɓuɓɓukan Mai Amfani",
    "Preferred Dialect": "Yaren da Aka Fi So",
    "Notification Mesh": "Kayan Sanarwa",
    "Protocol Interface": "Hanyar Yarjejeniya",
    "Linguistic preference synced": "An daidaita yarenku cikin nasara",
    "Sync fault in preferences": "An sami matsala wajen daidaita yare",
    "Notifications": "Sanarwa",
    "Dark Mode": "Yanayin Duhu",
    "Logout": "Fita",
    "Login": "Shiga",
    "Sign Up": "Rijista",
    "Profile": "Bayanai",
    "No notifications": "Babu sanarwa",
    "Support Center": "Cibiyar Taimako",
    "Legal Protocols": "Dokokin Shari'a",
    "About FindAba": "Game da FindAba",
    "Explore Aba": "Bincika Aba",
    "Find Opportunities": "Nemi Damammaki",
    "Search businesses": "Nemi kasuwanci...",
    "Trending Market Days": "Kwanakin Kasuwa",
    "Aba History description": "Aba birni ne mai cike da kasuwanci, masana'antu da al'adu.",
    "System Status": "Matsayin Tsarin",
    "Save Preferences": "Ajiye Zaɓuɓɓuka",
    "English (Official)": "Turanci (Ingilishi)",
    "Igbo (Zonal)": "Yaren Igbo",
    "Pidgin (Regional)": "Yaren Pidgin",
    "Yoruba": "Yaren Yoruba",
    "Hausa": "Yaren Hausa",
    "French": "Harshen Faransanci",
    "Chinese": "Harshen Sinanci",
    "Edit Profile": "Gyara Bayanai",
    "Security & Cryptography": "Tsaro & Boyayyar Magana"
  },
  pcm: {
    "City Faces": "Naija Faces",
    "Fidelity Wallet": "Fidelity Wallet",
    "Purple Fleet": "Purple Motor",
    "SANDALSroyalle Hotels & Suites": "Sandals Hotels",
    "Carry-Go Cargo": "Carry-Go Cargo",
    "Thrift Savings": "Ajo Savings",
    "Audio Archive": "Audio Archive",
    "Creative Lab": "Creative Lab",
    "Hardware Audit": "Hardware Check",
    "Aba History": "Aba Story",
    "City Registry": "City List",
    "Oracle Hub": "Oracle Hub",
    "Home Node": "Home",
    "System Settings": "System Settings",
    "User Preferences": "My Choice",
    "Preferred Dialect": "Language Blend",
    "Notification Mesh": "Alert System",
    "Protocol Interface": "Protocol Face",
    "Linguistic preference synced": "Language state update successfully",
    "Sync fault in preferences": "Language fail to sync",
    "Notifications": "Alerts",
    "Dark Mode": "Night View",
    "Logout": "Comot",
    "Login": "Enter",
    "Sign Up": "Join Us",
    "Profile": "My Profile",
    "No notifications": "No alerts dey",
    "Support Center": "Help Desk",
    "Legal Protocols": "Law Paper",
    "About FindAba": "About FindAba",
    "Explore Aba": "Waka Round Aba",
    "Find Opportunities": "Find Work and Business",
    "Search businesses": "Find shop and business...",
    "Trending Market Days": "Maket Days Wey Dey Run",
    "Aba History description": "Aba na pure commercial, industrial, and cultural power hub.",
    "System Status": "How System Dey",
    "Save Preferences": "Keep Settings",
    "English (Official)": "English",
    "Igbo (Zonal)": "Igbo",
    "Pidgin (Regional)": "Pidgin",
    "Yoruba": "Yoruba",
    "Hausa": "Hausa",
    "French": "French",
    "Chinese": "Chinese",
    "Edit Profile": "Change Setup",
    "Security & Cryptography": "Security Keys Setup"
  },
  pidgin: {
    "City Faces": "Naija Faces",
    "Fidelity Wallet": "Fidelity Wallet",
    "Purple Fleet": "Purple Motor",
    "SANDALSroyalle Hotels & Suites": "Sandals Hotels",
    "Carry-Go Cargo": "Carry-Go Cargo",
    "Thrift Savings": "Ajo Savings",
    "Audio Archive": "Audio Archive",
    "Creative Lab": "Creative Lab",
    "Hardware Audit": "Hardware Check",
    "Aba History": "Aba Story",
    "City Registry": "City List",
    "Oracle Hub": "Oracle Hub",
    "Home Node": "Home",
    "System Settings": "System Settings",
    "User Preferences": "My Choice",
    "Preferred Dialect": "Language Blend",
    "Notification Mesh": "Alert System",
    "Protocol Interface": "Protocol Face",
    "Linguistic preference synced": "Language state update successfully",
    "Sync fault in preferences": "Language fail to sync",
    "Notifications": "Alerts",
    "Dark Mode": "Night View",
    "Logout": "Comot",
    "Login": "Enter",
    "Sign Up": "Join Us",
    "Profile": "My Profile",
    "No notifications": "No alerts dey",
    "Support Center": "Help Desk",
    "Legal Protocols": "Law Paper",
    "About FindAba": "About FindAba",
    "Explore Aba": "Waka Round Aba",
    "Find Opportunities": "Find Work and Business",
    "Search businesses": "Find shop and business...",
    "Trending Market Days": "Maket Days Wey Dey Run",
    "Aba History description": "Aba na pure commercial, industrial, and cultural power hub.",
    "System Status": "How System Dey",
    "Save Preferences": "Keep Settings",
    "English (Official)": "English",
    "Igbo (Zonal)": "Igbo",
    "Pidgin (Regional)": "Pidgin",
    "Yoruba": "Yoruba",
    "Hausa": "Hausa",
    "French": "French",
    "Chinese": "Chinese",
    "Edit Profile": "Change Setup",
    "Security & Cryptography": "Security Keys Setup"
  },
  fr: {
    "City Faces": "Visages de la Ville",
    "Fidelity Wallet": "Portefeuille Fidelity",
    "Purple Fleet": "Flotte Violette",
    "SANDALSroyalle Hotels & Suites": "Hôtels Sandals",
    "Carry-Go Cargo": "Cargaison Carry-Go",
    "Thrift Savings": "Épargne Solidaire",
    "Audio Archive": "Archives Audio",
    "Creative Lab": "Laboratoire Créatif",
    "Hardware Audit": "Audit Matériel",
    "Aba History": "Histoire d'Aba",
    "City Registry": "Registre de la Ville",
    "Oracle Hub": "Pôle Oracle",
    "Home Node": "Accueil",
    "System Settings": "Paramètres Système",
    "User Preferences": "Préférences Utilisateur",
    "Preferred Dialect": "Langue Préférée",
    "Notification Mesh": "Réseau de Notifications",
    "Protocol Interface": "Interface Protocole",
    "Linguistic preference synced": "Préférence linguistique synchronisée",
    "Sync fault in preferences": "Défaut de synchronisation de la langue",
    "Notifications": "Notifications",
    "Dark Mode": "Mode Sombre",
    "Logout": "Se Déconnecter",
    "Login": "Se Connecter",
    "Sign Up": "S'inscrire",
    "Profile": "Mon Profil",
    "No notifications": "Aucune notification",
    "Support Center": "Centre d'Assistance",
    "Legal Protocols": "Protocoles Légaux",
    "About FindAba": "À Propos de FindAba",
    "Explore Aba": "Explorer Aba",
    "Find Opportunities": "Trouver des Opportunités",
    "Search businesses": "Rechercher des entreprises...",
    "Trending Market Days": "Jours de Marché",
    "Aba History description": "Aba est un centre commercial, industriel et culturel dynamique.",
    "System Status": "État du Système",
    "Save Preferences": "Enregistrer les Préférences",
    "English (Official)": "Anglais (Officiel)",
    "Igbo (Zonal)": "Igbo (Zonal)",
    "Pidgin (Regional)": "Pidgin (Régional)",
    "Yoruba": "Yoruba",
    "Hausa": "Haoussa",
    "French": "Français",
    "Chinese": "Chinois",
    "Edit Profile": "Modifier le Profil",
    "Security & Cryptography": "Sécurité & Cryptographie"
  },
  zh: {
    "City Faces": "城市面孔",
    "Fidelity Wallet": "Fidelity 钱包",
    "Purple Fleet": "紫色车队",
    "SANDALSroyalle Hotels & Suites": "Sandals 皇家酒店及套房",
    "Carry-Go Cargo": "Carry-Go 货运",
    "Thrift Savings": "互助储蓄 (Ajo)",
    "Audio Archive": "音频档案",
    "Creative Lab": "创意实验室",
    "Hardware Audit": "硬件审计",
    "Aba History": "阿巴历史",
    "City Registry": "城市登记处",
    "Oracle Hub": "Oracle 中心",
    "Home Node": "主页",
    "System Settings": "系统设置",
    "User Preferences": "用户偏好",
    "Preferred Dialect": "首选语言",
    "Notification Mesh": "通知网络",
    "Protocol Interface": "协议接口",
    "Linguistic preference synced": "语言偏好已同步",
    "Sync fault in preferences": "语言偏好同步错误",
    "Notifications": "通知",
    "Dark Mode": "深色模式",
    "Logout": "登出",
    "Login": "登录",
    "Sign Up": "注册",
    "Profile": "个人资料",
    "No notifications": "暂无通知",
    "Support Center": "支持中心",
    "Legal Protocols": "法律协议",
    "About FindAba": "关于 FindAba",
    "Explore Aba": "探索阿巴",
    "Find Opportunities": "寻找商机",
    "Search businesses": "搜索企业...",
    "Trending Market Days": "热门集市日",
    "Aba History description": "阿巴是一个充满活力的商业、工业和文化中心。",
    "System Status": "系统状态",
    "Save Preferences": "保存偏好设置",
    "English (Official)": "英语 (官方)",
    "Igbo (Zonal)": "伊博语 (区域)",
    "Pidgin (Regional)": "皮钦语 (地方)",
    "Yoruba": "约鲁巴语",
    "Hausa": "豪萨语",
    "French": "法语",
    "Chinese": "中文",
    "Edit Profile": "编辑个人资料",
    "Security & Cryptography": "安全与密码学"
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { profile } = useAuth();
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('findaba_lang') as LanguageCode;
    return saved || 'en';
  });

  // Synchronize with user profile when profile is fetched or updated
  useEffect(() => {
    if (profile?.preferred_language) {
      const dbLang = profile.preferred_language.toLowerCase() as LanguageCode;
      if (dbLang && TRANSLATIONS[dbLang]) {
        setLanguageState(dbLang);
        localStorage.setItem('findaba_lang', dbLang);
      }
    }
  }, [profile?.preferred_language]);

  const setLanguage = async (newLang: LanguageCode) => {
    if (!TRANSLATIONS[newLang]) return;
    setLanguageState(newLang);
    localStorage.setItem('findaba_lang', newLang);
  };

  const t = (key: string, fallback?: string): string => {
    const activeLang = TRANSLATIONS[language] || TRANSLATIONS.en;
    if (activeLang && activeLang[key]) {
      return activeLang[key];
    }
    // Fall back to English
    const englishLang = TRANSLATIONS.en;
    if (englishLang && englishLang[key]) {
      return englishLang[key];
    }
    return fallback !== undefined ? fallback : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
