
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

interface WaybillData {
  orderId: string;
  trackingId?: string;
  customerName: string;
  customerPhone?: string;
  customerAddress?: string;
  merchantName: string;
  pickupAddr: string;
  dropoffAddr: string;
  amount: number;
  itemDescription?: string;
  date: string;
}

export const generateWaybillPDF = (data: WaybillData) => {
  const doc = new jsPDF();
  const primaryColor = '#008c52'; // Aba Green
  const accentColor = '#FFD700'; // Aba Gold
  
  // Header
  doc.setFillColor(30, 0, 51); // Dark Purple
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('FIN D ABA | LOGISTICS', 20, 25);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('OFFICIAL INDUSTRIAL WAYBILL', 20, 32);
  
  doc.setTextColor(accentColor);
  doc.text(`ORDER: ${data.orderId.slice(-8).toUpperCase()}`, 150, 25);
  doc.text(`DATE: ${data.date}`, 150, 32);
  if (data.trackingId) {
    doc.text(`TRACKING: ${data.trackingId}`, 150, 39);
  }

  // Main Content
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.text('INDUSTRIAL HANDSHAKE ARTIFACT', 20, 55);
  doc.setLineWidth(0.5);
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 58, 190, 58);

  const shipmentTable = [
    ['Merchant Partner', data.merchantName],
    ['Customer Name', data.customerName],
    ['Customer Phone', data.customerPhone || 'N/A'],
    ['Customer Address', data.customerAddress || 'N/A'],
    ['Pickup Location', data.pickupAddr],
    ['Delivery Location', data.dropoffAddr],
    ['Item Signal', data.itemDescription || 'General Industrial Cargo'],
    ['Declared Value', `NGN ${data.amount.toLocaleString()}`],
  ];

  (doc as any).autoTable({
    startY: 65,
    head: [['Registry Field', 'Verified Signal Details']],
    body: shipmentTable,
    theme: 'striped',
    headStyles: { fillColor: primaryColor, textColor: 255 },
    styles: { fontSize: 10, cellPadding: 5 }
  });

  // Footer / Legal section
  const finalY = (doc as any).lastAutoTable.finalY + 20;
  doc.setFontSize(14);
  doc.text('SECURITY & VERIFICATION', 20, finalY);
  doc.line(20, finalY + 3, 190, finalY + 3);

  doc.setFontSize(10);
  doc.text('This document is generated by the FindAba Industrial OS.', 20, finalY + 15);
  doc.text('The shipment tracking ID is tied to the merchant node heartbeat.', 20, finalY + 22);

  // QR Code Placeholder or footer
  const footerY = 270;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('FindAba Industrial Registry Handshake Verified.', 20, footerY);
  doc.text('This waybill serves as a digital legal artifact for the Enyimba Logistics Network.', 20, footerY + 5);
  
  // Blue signature line
  doc.setDrawColor(0, 140, 82);
  doc.line(140, footerY, 190, footerY);
  doc.text('Authorized Registry Stamp', 145, footerY + 5);

  doc.save(`waybill-${data.orderId.slice(-8)}.pdf`);
};
