
import { lazy } from 'react';
import { ViewState } from '../types';

export const ROUTE_MAP: Record<ViewState, any> = {
  home: lazy(() => import('../features/discovery/Home')),
  discover: lazy(() => import('../features/discovery/Discover')),
  explore: lazy(() => import('../features/discovery/Explore')),
  detail: lazy(() => import('../features/discovery/BusinessDetail')),
  editorial: lazy(() => import('../features/discovery/AdvertorialFeed')),
  'editorial-detail': lazy(() => import('../features/discovery/AdvertorialDetail')),
  feed: lazy(() => import('../features/faces/FacesFeed')),
  'merchant-portal': lazy(() => import('../features/merchant/MerchantPortal')),
  register: lazy(() => import('../features/merchant/Register')),
  pricing: lazy(() => import('../features/merchant/Pricing')),
  'ad-checkout': lazy(() => import('../features/discovery/AdCheckout')),
  'business-verification': lazy(() => import('../features/merchant/BusinessVerification')),
  oracle: lazy(() => import('../features/oracle/Oracle')),
  about: lazy(() => import('../features/info/About')),
  'about-aba': lazy(() => import('../features/info/AboutAba')),
  legal: lazy(() => import('../features/info/Legal')),
  support: lazy(() => import('../features/discovery/Home')),
  orders: lazy(() => import('../features/finance/BuyerOrdersView')),
  'dispute-center': lazy(() => import('../features/discovery/Home')),
  
  // Fillers for other types to avoid exhaustive errors if needed
  lab: lazy(() => import('../features/creative/CreativeLab')),
  cargo: lazy(() => import('../features/logistics/Logistics')),
  profile: lazy(() => import('../features/auth/Profile')),
  messages: lazy(() => import('../features/oracle/ChatView')),
  admin: lazy(() => import('../features/admin/Admin')),
  'srts-dashboard': lazy(() => import('../features/logistics/CarryGoDash')),
  'buyer-portal': lazy(() => import('../features/finance/BuyerPortal')),
  'ad-manager': lazy(() => import('../features/merchant/AdManager')),
  'registry-setup': lazy(() => import('../features/tech/RegistrySetup')),
  'sandals-hotels': lazy(() => import('../features/hospitality/SandalsHotels')),
  wallet: lazy(() => import('../features/finance/WalletView')),
  contact: lazy(() => import('../features/info/Contact')),
  'audio-heritage': lazy(() => import('../features/creative/AudioHeritage')),
  'srts-office': lazy(() => import('../features/admin/SandalsOffice')),
  'booking-ledger': lazy(() => import('../features/hospitality/HotelLedger')),
  'hotel-detail': lazy(() => import('../features/discovery/Home')),
  'hotel-partner-control': lazy(() => import('../features/hospitality/HotelPartnerControl')),
  'about-who': lazy(() => import('../features/info/About')),
  'about-vision': lazy(() => import('../features/info/About')),
  'about-mission': lazy(() => import('../features/info/About')),
  login: lazy(() => import('../features/auth/Login')),
  signup: lazy(() => import('../features/auth/Login')),
  'carry-me': lazy(() => import('../features/logistics/CarryMe')),
  'driver-registry': lazy(() => import('../features/logistics/DriverRegistry')),
  'purple-fleet': lazy(() => import('../features/logistics/PurpleFleet')),
  'driver-console': lazy(() => import('../features/logistics/DriverConsole')),
  'fleet-admin': lazy(() => import('../features/logistics/FleetAdmin')),
  'hardware-audit': lazy(() => import('../features/tech/HardwareAudit')),
  'carry-go-dash': lazy(() => import('../features/logistics/CarryGoDash')),
  onboarding: lazy(() => import('../features/auth/Onboarding'))
};
